# Generated by Django 3.0.6 on 2020-05-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=512)),
                ('subject', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
            ],
        ),
    ]
