# Generated by Django 3.0.6 on 2020-05-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.TextField(),
        ),
    ]
